### ISSUE TITLE
Add the Updates Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-referral#24]
![Picture2](https://user-images.githubusercontent.com/20777928/77567921-e740db00-6ed8-11ea-8839-70d7bae4aca8.png)

- [ ] All referral closure and Health Facility key events (i.e. Sick child, malaria follow-up, ANC or PNC danger signs) associated with clients in the CHW's catchment area will appear ther
- [x] Top left menu button opens side menu (#23  )
- [x] Swiping from the left also opens side menu (#23 )
- [x] Dynamic search bar (#25  )
- [x] There is NO Due only toggle
- [x] Row text display ( #26 )
- [x] Client rows are organized from the most newest to the oldest
- [x] Client row arrow takes you to the detailed notification information
